http:
  port: "8081"
  
american:
  host: "training4-american-api-anand2.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: a5f4740055ce449a9683f5c1d673cfeb
  client_secret: Db012d7c541F44Cd91494Ed9171168fd
  
training:
  host: "ilt.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://ilt.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"